# Generated by Django 5.1 on 2024-09-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eco', '0003_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='product',
        ),
    ]
