# Generated by Django 5.1 on 2024-10-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eco', '0005_payment_orderplace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplace',
            old_name='ordered_data',
            new_name='ordered_date',
        ),
    ]
